### PR TITLE
Give doozer a top level --version option

### PR DESCRIPTION
**Pull request by tbielawa**

### CODE REVIEW

**Comment by adammhaile** [comment]
Nice, but I would like to consolidate where version is stored. It should read that value from somewhere that setup.py can get to as well so we only have to change it in one place. I have some example code of how I've done it before... will come back to this.

**Comment by adammhaile** [comment]
Also, yes we should make it 0.2.0 or whatever. I meant to do that.

**Comment by tbielawa** [comment]
Glad you agree, wrt: where it's stored.

https://click.palletsprojects.com/en/6.x/api/#click.version_option

```
Parameters
version – the version number to show. If not provided Click attempts an auto discovery via setuptools.
```

They just don't tell us HOW it tries to figure that out. When I tried using it implicitly it failed :'(

**Comment by adammhaile** [comment]
Ok, I'll take a look.

**Comment by tbielawa** [comment]
Superseded by #12.

**Pull request closed without merging**
