### PR TITLE
Merge multi & single arch gen-payload

### PR DESCRIPTION
**Pull request by jupierce**

### CODE REVIEW

**Comment by vfreex** [comment]
@jupierce Those 2 commands have different argument names and could break our Jenkins jobs.
https://github.com/openshift/aos-cd-jobs/pull/2039 seems to be related but I still found another place that `release:gen-payload` is called: https://github.com/openshift/aos-cd-jobs/blob/914ea8ba512575291b005b238d03af33316099c6/jobs/build/build-sync/build.groovy#L105

LGTM but would like to hold this until those Jenkins job changes are ready.

/lgtm
/hold

**Comment by jupierce** [comment]
@vfreex https://github.com/openshift/aos-cd-jobs/pull/2039 is definitely related, but I'm not sure that there is anything missing there. The line you mention (105) of build.groovy is removed in the PR:
https://github.com/openshift/aos-cd-jobs/pull/2039/files#diff-bee14b23497d68b2e2b4e173872ac1acL105

**Comment by vfreex** [comment]
@jupierce Thanks for pointing to that which I didn't noticed. It could be hard to review the PR without necessary context. Could you help link related PRs next time?

I made a comment on the linked PR.

/hold cancel

**Comment by vfreex** [comment]
LGTM and tested this PR without any issues:

``` bash
doozer -g openshift-4.2 -i cluster-version-operator  release:gen-payload --is-name 4.2-art-latest --organization openshift-release-dev --repository ocp-v4.0-art-dev
```

got 

```
src_dest.x86_64
registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-cluster-version-operator@sha256:a1d577b9bf1b52621882c62b89df46a3fac5212c6779f76819d016a39ec8e22a=quay.io/openshift-release-dev/ocp-v4.0-art-dev:v4.2.15-202001100432-ose-cluster-version-operator

src_dest.s390x
registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-cluster-version-operator@sha256:565c93e9a09ada7393061d5ccb716d603fc477fe5d5aedb0c287ac273a378b40=quay.io/openshift-release-dev/ocp-v4.0-art-dev:v4.2.15-202001100432-s390x-ose-cluster-version-operator

image_stream.x86_64
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: 4.2-art-latest
  namespace: ocp
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/openshift-release-dev/ocp-v4.0-art-dev:v4.2.15-202001100432-ose-cluster-version-operator
    name: cluster-version-operator

image_stream.s390x
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: 4.2-art-latest-s390x
  namespace: ocp-s390x
spec:
  tags:
  - from:
      kind: DockerImage
      name: quay.io/openshift-release-dev/ocp-v4.0-art-dev:v4.2.15-202001100432-s390x-ose-cluster-version-operator
    name: cluster-version-operator

```

/lgtm

**Pull request merged**
