### PR TITLE
Adding Cluster Service Version processing

### PR DESCRIPTION
**Pull request by adammhaile**
@smunilla @tbielawa PTAL
Haven't had a lot of testing time on this but it does work with config changes I added -> https://github.com/openshift/ocp-build-data/commit/629dff37a050fd0f769fdd9171823b825d508bcb
And wanted to get it in a PR before the break.

This will probably change as we add more operators but it works with the info we have now and I've confirmed it updates the csv file as desired.

### CODE REVIEW

**Comment by adammhaile** [comment]
FYI, this would be the only test that will do much with this -> `doozer --data-path ~/src/ocp-build-data/ --group openshift-4.1 -i openshift-enterprise-ansible-operator,openshift-enterprise-ansible-service-broker-operator,openshift-enterprise-asb images:rebase --version v4.1.0 --release 201904181516 --repo-type unsigned -m "Test" --no-push`

Remove `openshift-enterprise-asb` to see it late-load that image data and find it's most recent build to inject into the csv yaml file.

**Comment by tbielawa** [comment]
Seems legit to me

**Comment by tbielawa** [comment]
It did a thing! I mean, I think it did. I'm not sure how to tell what it did. I did with and without -asb. 

What should I be expecting to see here?

```
$ ./doozer --group openshift-4.1 -i openshift-enterprise-ansible-operator,openshift-enterprise-ansible-service-broker-operator images:rebase --version v4.1.0 --release 201904181516 --repo-typ
e unsigned -m "Test" --no-push
2019-04-18 15:14:01,192 INFO Data clone directory already exists, checking commit sha
2019-04-18 15:14:03,429 INFO git@github.com:openshift/ocp-build-data.git is already cloned and latest
/home/tbielawa/.local/lib/python2.7/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly ad
vised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2019-04-18 15:14:04,411 INFO Using branch from group.yml: rhaos-4.1-rhel-7
2019-04-18 15:14:04,788 INFO [containers/openshift-enterprise-ansible-operator] Distgit directory already exists; skipping clone: /home/tbielawa/doozer/distgits/containers/openshift-enterpris
e-ansible-operator
2019-04-18 15:14:04,788 INFO [containers/openshift-enterprise-ansible-service-broker-operator] Distgit directory already exists; skipping clone: /home/tbielawa/doozer/distgits/containers/open
shift-enterprise-ansible-service-broker-operator
2019-04-18 15:14:05,008 INFO Source 'openshift-enterprise-ansible-operator_ocp-release-operator-sdk' already exists in (skipping clone): /home/tbielawa/doozer/sources/openshift-enterprise-ans
ible-operator_ocp-release-operator-sdk
2019-04-18 15:14:05,429 INFO [containers/openshift-enterprise-ansible-operator] Adding commit to local repo: Test
2019-04-18 15:14:05,654 INFO [containers/openshift-enterprise-ansible-operator] Adding tag to local repo: v4.1.0-201904181516
2019-04-18 15:14:05,661 INFO Source 'openshift-enterprise-ansible-service-broker-operator_ansible-service-broker' already exists in (skipping clone): /home/tbielawa/doozer/sources/openshift-e
nterprise-ansible-service-broker-operator_ansible-service-broker
2019-04-18 15:14:06,502 INFO [containers/openshift-enterprise-ansible-service-broker-operator] Adding commit to local repo: Test
2019-04-18 15:14:06,564 INFO [containers/openshift-enterprise-ansible-service-broker-operator] Adding tag to local repo: v4.1.0-201904181516
```

**Comment by adammhaile** [comment]
This file should get updated:
`${WORKSPACE}/distgits/containers/openshift-enterprise-ansible-service-broker-operator/deploy/olm-catalog/openshift-ansible-service-broker-manifests/4.1/openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml`

**Comment by tbielawa** [comment]
/lgtm

I see it!

```diff
$ diff -Naur openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml.second 
--- openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml     2019-04-18 15:29:01.680162473 -0500
+++ openshiftansibleservicebroker.v4.1.0.clusterserviceversion.yaml.second      2019-04-18 15:29:39.956935530 -0500
@@ -211,7 +211,7 @@
                 imagePullPolicy: IfNotPresent
                 env:
                 - name: IMAGE
-                  value: quay.io/openshift/ose-ansible-service-broker:v4.1.0-201904181516
+                  value: quay.io/openshift/ose-ansible-service-broker:v4.1.0-201904171555
                 - name: OPERATOR_NAME
                   value: openshift-ansible-service-broker-operator
                 - name: POD_NAME
```

**Comment by adammhaile** [comment]
Thanks @tbielawa and @shiywang 
Since everyone's off and there's no rush on this till next week, I'm going to leave this unmerged for now. 
Will be out on Monday, so feel free to merge it if it's deemed immediately necessary.

**Pull request merged**
