### PR TITLE
[ART-1311] Drop Python2 support

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by vfreex** [comment]
Would also like to remove Python 2.7 info from setup.py. otherwise LGTM.

**Comment by vfreex** [comment]
The unit test failure is not related to this PR, which is broken on master. https://github.com/openshift/doozer/pull/180 has the unit test fix

**Comment by thiagoalessio** [comment]
@vfreex setup.py done :heavy_check_mark:

**Comment by vfreex** [comment]
LGTM, but needs to wait for @sosiouxme 's confirmation with other users:

> @sosiouxme: I'm asking our only other user if it's ok to drop support for py 2.7. Hopefully it's not a problem.


/lgtm
/hold

**Comment by sosiouxme** [comment]
/hold cancel
we're good, let's do this.

**Pull request merged**
