### PR TITLE
2020 01 30 add extra repo configs to group yml

### PR DESCRIPTION
**Pull request by tbielawa**
RE: https://issues.redhat.com/browse/ART-1385

Enables arbitrary extra yum repo options to be set in container dist-git repo files.

```    Enable addition of arbitrary extra yum options via group.yml
    
    re: https://issues.redhat.com/browse/ART-1385 "Use golang 1.13 to
    compile 4.4 (el8)"
    
    This more immediately provides us with a work-around to a yum module
    error we were experiencing while building the new golang-builder
    container.
    
    Example usage:
    
      Add an 'extra_options' section under the 'conf' key in your
      group.yml file like this:
    
        repos:
          rhel-8-server-ose-build-rpms:
            conf:
              extra_options:
                module_hotfixes: 1
    
              baseurl:
                ...
    
      Then after your next 'images:rebase' the 'module_hotfixes' key will
      be set in each 'rhel-8-server-ose-build-rpms' repo section in
      .oit/[un]signed.repo in dist-git.
```

### CODE REVIEW

**Comment by tbielawa** [comment]
Found a lil' buggie. It started printing the python dict struct in the repo conf....
http://download.eng.bos.redhat.com/brewroot/work/tasks/8407/26158407/x86_64.log

```ini
[rhel-8-server-ose-build-rpms-x86_64]
extra_options = {'module_hotfixes': 1}
gpgcheck = 0
enabled = 1
baseurl = http://download-node-02.eng.bos.redhat.com/brewroot/repos/rhaos-4.4-rhel-8-build/latest/x86_64/
name = rhel-8-server-ose-build-rpms-x86_64

[rhel-8-server-ose-build-rpms-ppc64le]
extra_options = {'module_hotfixes': 1}
gpgcheck = 0
enabled = 1
baseurl = http://download-node-02.eng.bos.redhat.com/brewroot/repos/rhaos-4.4-rhel-8-build/latest/ppc64le/
name = rhel-8-server-ose-build-rpms-ppc64le

[rhel-8-server-ose-build-rpms-s390x]
extra_options = {'module_hotfixes': 1}
gpgcheck = 0
enabled = 1
baseurl = http://download-node-02.eng.bos.redhat.com/brewroot/repos/rhaos-4.4-rhel-8-build/latest/s390x/
name = rhel-8-server-ose-build-rpms-s390x
```

**Comment by vfreex** [comment]
/lgtm
Would like to bump the version at the same time.

**Pull request merged**
