### PR TITLE
Adding branch reporting functions

### PR DESCRIPTION
**Pull request by adammhaile**
I'm not married to how I implemented the new interface. Started as quick and dirty but I liked the feature so didn't want to just throw away the work.

### CODE REVIEW

**Comment by tbielawa** [comment]
New stuff. Seems good.
/lgtm

**Comment by tbielawa** [comment]
New stuff. Seems good.
/lgtm

**Comment by sosiouxme** [comment]
```
🐚 ./doozer -g openshift-4.1 -i ose-metering-helm clone-sources 
2019-05-16 03:33:45,990 INFO Using branch from group.yml: rhaos-4.1-rhel-7
2019-05-16 03:33:46,386 INFO Checking if target branch release-4.1 exists in git@github.com:operator-framework/helm.git
2019-05-16 03:33:46,828 INFO Attempting to checkout source 'git@github.com:operator-framework/helm.git' branch release-4.1 in: /tmp/working/sources/ose-metering-helm_helm
2019-05-16 03:33:55,300 INFO Registering source alias ose-metering-helm_helm: /tmp/working/sources/ose-metering-helm_helm
2019-05-16 03:33:55,310 INFO Checking if target branch release-4.1 exists in git@github.com:openshift/openshift-ansible.git
2019-05-16 03:33:55,960 INFO Attempting to checkout source 'git@github.com:openshift/openshift-ansible.git' branch release-4.1 in: /tmp/working/sources/rpm_openshift-ansible_openshift-ansible
2019-05-16 03:33:57,759 INFO Registering source alias rpm_openshift-ansible_openshift-ansible: /tmp/working/sources/rpm_openshift-ansible_openshift-ansible
2019-05-16 03:33:57,767 INFO Checking if target branch release-4.1 exists in git@github.com:openshift/service-idler.git
2019-05-16 03:33:58,260 INFO Target branch does not exist in git@github.com:openshift/service-idler.git, checking fallback branch master
2019-05-16 03:33:58,261 INFO Checking if target branch master exists in git@github.com:openshift/service-idler.git
```
uh... why does it keep going?

**Comment by sosiouxme** [comment]
```
🐚 ./doozer -g openshift-4.1 -i ose-metering-helm config:scan-sources
2019-05-16 03:36:16,136 INFO Using branch from group.yml: rhaos-4.1-rhel-7
Traceback (most recent call last):
  File "./doozer", line 1853, in <module>
    main()
  File "./doozer", line 1834, in main
    cli(obj={})
  File "/home/lmeyer/.local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/lmeyer/.local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/lmeyer/.local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lmeyer/.local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lmeyer/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lmeyer/.local/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/lmeyer/.local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "./doozer", line 404, in config_scan_source_changes
    for meta, matches in runtime.scan_distgit_sources():
  File "/home/lmeyer/go/src/github.com/openshift/doozer/doozerlib/runtime.py", line 957, in scan_distgit_sources
    n_threads=100,
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
doozerlib.runtime.WrapException: 
Original traceback:
Traceback (most recent call last):
  File "/home/lmeyer/go/src/github.com/openshift/doozer/doozerlib/runtime.py", line 78, in wrapper
    return func(*args, **kwargs)
  File "/home/lmeyer/go/src/github.com/openshift/doozer/doozerlib/runtime.py", line 955, in <lambda>
    lambda m: (m[0], m[0].distgit_repo(autoclone=False).matches_source_commit(builds)),
  File "/home/lmeyer/go/src/github.com/openshift/doozer/doozerlib/distgit.py", line 233, in matches_source_commit
    _, commit_hash = self.runtime.detect_remote_source_branch(dict(source_details))
TypeError: detect_remote_source_branch() takes exactly 3 arguments (2 given)
```

y'know what would really make this great... some unit tests :)

**Comment by adammhaile** [comment]
A) no idea why it keeps going... worked for me. Will test some more.
B) I didn't even touch that code. Looking...

**Comment by sosiouxme** [comment]
If it helps, I rebased on master and I already had a number of repos cloned in my workspace.

**Comment by adammhaile** [comment]
Yeah... I'm seeing the issues now with it being updated and I am in fact
finding similar issues now, depending on what's already in my workspace.
Will take more testing. Not really important though... so I'll fix it up as
I have time.
Thanks Luke :)

**Pull request closed without merging**
