### PR TITLE
Make KUBE_GIT_VERSION historically consistent

### PR DESCRIPTION
**Pull request by jupierce**
The old tito flow called bash, which called go, which went through a sed, and back into tito. While stripping out tito, I missed that `KUBE_GIT_VERSION` would be munged from an actual version like `v1.14.6-152-g117ba1f` to vM.N.P+OS_GIT_VERSION. 
Easier to see what changed if you hide whitespace: https://github.com/openshift/doozer/pull/213/files?diff=split&w=1

### CODE REVIEW

**Comment by jupierce** [comment]
@thiagoalessio new validation rules enabled for CI?

**Comment by thiagoalessio** [comment]
@jupierce [flake8](https://pypi.org/project/flake8/#history) got recently updated (from **3.7.9** to **3.8.1**), which brought newer versions of two dependencies:
- [pycodestyle](https://pypi.org/project/pycodestyle/2.6.0/) from **2.5.0** to **2.6.0**
- [pyflakes](https://github.com/PyCQA/pyflakes/blob/master/NEWS.rst) from **2.1.1** to **2.2.0**

On their respective changelogs, I found the following entries:

**pycodestyle**
> 2.6.0a1 (2020-04-23)
> ...
> Changes:
>     E741: allow l as a named argument in a function call. PR #853.

**pyflakes**

> 2.2.0 (2020-04-08)
> ... 
>     Add check for f-strings without placeholders

I just fixed those complains directly on master (https://github.com/openshift/doozer/commit/745ada6c6a517e61ac3357e6e972eda679c63d27). You can just rebase and the errors will _hopefully_ be gone.

**Comment by thiagoalessio** [comment]
@jupierce [flake8](https://pypi.org/project/flake8/#history) got recently updated (from **3.7.9** to **3.8.1**), which brought newer versions of two dependencies:
- [pycodestyle](https://pypi.org/project/pycodestyle/2.6.0/) from **2.5.0** to **2.6.0**
- [pyflakes](https://github.com/PyCQA/pyflakes/blob/master/NEWS.rst) from **2.1.1** to **2.2.0**

On their respective changelogs, I found the following entries:

**pycodestyle**
> 2.6.0a1 (2020-04-23)
> ...
> Changes:
>     E741: allow l as a named argument in a function call. PR #853.

**pyflakes**

> 2.2.0 (2020-04-08)
> ... 
>     Add check for f-strings without placeholders

I fixed those complaints directly on master (https://github.com/openshift/doozer/commit/745ada6c6a517e61ac3357e6e972eda679c63d27). You can just rebase and the errors will _hopefully_ be gone.

**Comment by thiagoalessio** [comment]
elliott had similar issues since flake8 update. Fixed: https://github.com/openshift/elliott/commit/23a6bba5f0342affc10a176422dff9323402e185

**Pull request merged**
