### PR TITLE
Allow group.yml to disable builds

### PR DESCRIPTION
**Pull request by jupierce**
`freeze_automation: yes`  - prevent all builds, including from command line (enforced by doozer)
`freeze_automation: no` - don't prevent any builds 
`freeze_automation: scheduled` - prevent scheduled builds, but nothing manual (enforced by pipeline code which should query doozer group with config:read-group)

### CODE REVIEW

**Comment by sosiouxme** [comment]
1. `image:rebase` should also check whether builds are permitted
2. the group.yml schema isn't really used by anything AFAIK -- our validation is in ocp-build-data-validator so that at least would need an update here.

**Comment by jupierce** [comment]
@sosiouxme I don't see any group validation in https://github.com/openshift/ocp-build-data-validator .

**Comment by vfreex** [comment]
@jupierce I think this PR belongs to what we talked at the Arch meeting?
Regarding RFEs, will you open other PRs or update this PR?

**Comment by sosiouxme** [comment]
Alright, I think it's good. We'll find out soon enough if there's any actual validation on group.yml schema...

**Pull request merged**
