### PR TITLE
Refactoring: Move entrypoint to doozerlib/cli/__main__.py

### PR DESCRIPTION
**Pull request by vfreex**
This PR
    
- moves entrypoint to `doozerlib/cli/__main__.py`, so that you can run doozer with `python2 -m doozerlib` or `python3 -m doozerlib`. A new `doozer` script is created for local testing but will not be installed for production.
- updates `setup.py` to create a launch script so that we don't need to worry about python interpretor path (`/usr/bin/python` or `/usr/bin/python3`). `pip` will handle it automatically during installation process.
- sets `classifiers` attribute for PyPI.
- moves dev dependencies (autopep8, coverage, flake8, ...) to `requirements-dev.txt` and makes `tox.ini` honor it.
- updates dev container configuration accordingly.

### CODE REVIEW

**Comment by vfreex** [comment]
Also fixed the flake8 issue.

**Comment by vfreex** [comment]
Like https://github.com/openshift/elliott/pull/77, changed target branch to `master` for refactoring and will open other PRs for Python-3 migration.

**Comment by thiagoalessio** [comment]
@vfreex i like the changes, will be much easier to add tests for the main CLI entrypoint now!!!
apparently there are some conflicts that are preventing the merge ... apart from that, LGTM.

**Comment by vfreex** [comment]
@thiagoalessio Thanks. I've done a rebase.

**Pull request merged**
